assignees:
  - caufieldjh
body:
  - attributes:
      value: This is the form for requesting a new entity (e.g., a data standard, tool, or topic) in the Bridge2AI Standards Registry.
    type: markdown
  - id: entity_type
    attributes:
      description: What kind of thing is this?
      label: Entity Type
      multiple: false
      options:
        - Data Standard or Tool
        - Data Substrate
        - Data Topic
        - Organization
        - Use Case
    type: dropdown
    validations:
      required: true
  - id: category
    attributes:
      description: What should the category be, based on the classes of the Bridge2AI Standards Schemas (https://bridge2ai.github.io/standards-schemas/)? If in doubt, leave blank.
      label: Category
      placeholder: NamedThing
    type: input
  - id: name
    attributes:
      description: What is the short name of this entity? An acronym or short phrase works best.
      label: Name
      placeholder: e.g., ESM Atlas, W3C, Molecular Biology
    type: input
    validations:
      required: true
  - id: description
    attributes:
      description: What is the extended name of this entity?
      label: Description
      placeholder: e.g., ESM Metagenomic Atlas or World Wide Web Consortium
    type: input
    validations:
      required: true
  - id: purpose_detail
    attributes:
      description: What is the description of this entity, in a sentence or two?
      label: Purpose Detail
      placeholder: e.g., Any data concerning studies of the structure, function, and interactions of biological molecules.
    type: input
    validations:
      required: false
  - id: subclass_of
    attributes:
      description: (Optional) Is this a subclass of another entity? Please use an identifier.
      label: Subclass_Of
      placeholder: e.g., "B2AI_TOPIC:5"
    type: input
    validations:
      required: false
  - id: related_to
    attributes:
      description: (Optional) Is this related to another entity? Please list identifiers on separate lines.
      label: Related_To
      placeholder: e.g., "B2AI_TOPIC:5"
    type: textarea
    validations:
      required: false
  - id: contributor_name
    attributes:
      description: What is your name? This will be used for attribution.
      label: Contributor Name
      placeholder: e.g., Tabatha Butterscotch
    type: input
    validations:
      required: true
  - id: contributor_github
    attributes:
      description: What is your GitHub name, without the @ symbol?
      label: Contributor GitHub
      placeholder: e.g., tbuttersco
    type: input
    validations:
      required: true
  - id: contributor_orcid
    attributes:
      description: What is your ORCID iD?
      label: Contributor ORCID
      placeholder: e.g., 0000-0001-2345-6789
    type: input
    validations:
      required: true
description: Request addition of something new to the registry, including standards, concepts, use cases.
labels:
  - New
name: Request new entity
title: Add this entity - [Name Here]
