name: Request new entity
description: Request addition of something new to the registry, including standards, concepts, use cases.
title: Add this entity - [Name Here]
labels: [ New ]
assignees:
  - caufieldjh
body:
  - type: markdown
    attributes:
      value: This is the form for requesting a new entity (e.g., a data standard, tool, or topic) in the Bridge2AI Standards Registry.
  - type: dropdown
    id: entity_type
    attributes:
      label: Entity Type
      description: What kind of thing is this?
      multiple: false
      options:
        - Data Standard or Tool
        - Data Substrate
        - Data Topic
        - Organization
        - Use Case
    validations:
      required: true
  - type: input
    id: category
    attributes:
      label: Category
      description: What should the category be, based on the classes of the Bridge2AI Standards Schemas (https://bridge2ai.github.io/standards-schemas/)? If in doubt, leave blank.
      placeholder: NamedThing
  - type: input
    id: name
    attributes:
      label: Name
      description: What is the short name of this entity? An acronym or short phrase works best.
      placeholder: e.g., ESM Atlas, W3C, Molecular Biology
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Description
      description: What is the extended name of this entity?
      placeholder: e.g., ESM Metagenomic Atlas or World Wide Web Consortium
    validations:
      required: true
  - type: input
    id: purpose_detail
    attributes:
      label: Purpose Detail
      description: What is the description of this entity, in a sentence or two?
      placeholder: e.g., Any data concerning studies of the structure, function, and interactions of biological molecules.
    validations:
      required: false
  - type: input
    id: subclass_of
    attributes:
      label: Subclass_Of
      description: (Optional) Is this a subclass of another entity? Please use an identifier.
      placeholder: e.g., "B2AI_TOPIC:5"
    validations:
      required: false
  - type: textarea
    id: related_to
    attributes:
      label: Related_To
      description: (Optional) Is this related to another entity? Please list identifiers on separate lines.
      placeholder: e.g., "B2AI_TOPIC:5"
    validations:
      required: false
  - type: input
    id: contributor_name
    attributes:
      label: Contributor Name
      description: What is your name? This will be used for attribution.
      placeholder: e.g., Tabatha Butterscotch
    validations:
      required: true
  - type: input
    id: contributor_github
    attributes:
      label: Contributor GitHub
      description: What is your GitHub name, without the @ symbol?
      placeholder: e.g., tbuttersco
    validations:
      required: true
  - type: input
    id: contributor_orcid
    attributes:
      label: Contributor ORCID
      description: What is your ORCID iD?
      placeholder: e.g., 0000-0001-2345-6789
    validations:
      required: true
